[package]
name = "image_deduplicator"
version = "0.1.0"
authors = ["essenius <essenius@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.1"
#image = "0.23.9"
filetime = "0.2"
